// Data Store for Anh Đào Carrick (FCCA) - ACCA Certified Accounting Practice
// ACCREDITATION: ACCA / FCCA (Fellow Chartered Certified Accountant) - Direct Practice

const TRANSLATIONS = {
  en: {
    nav: {
      home: "Home",
      about: "About Mrs. Anh Đào Carrick",
      services: "Accounting & Tax Services",
      sectors: "Sectors We Serve",
      deadlines: "Tax Calendar",
      offices: "London Office",
      contact: "Contact",
      tagline: "ACCA Accountant"
    },
    hero: {
      badge: "🇬🇧 ACCA Regulated UK Accounting Practice",
      title: "Accounting, Tax & Advisory Services for UK Vietnamese Businesses & Investors",
      subtitle: "Professional statutory accounting, HMRC tax compliance, company formations, and business advisory led directly by Mrs. Anh Đào Carrick (BA, PG Cert, MA, FCCA).",
      ctaWhatsApp: "💬 Chat on WhatsApp",
      ctaZalo: "💬 Chat on Zalo",
      ctaConsultation: "Get a Free Quote",
      stat1Title: "FCCA Qualified",
      stat1Desc: "Fellow Member of ACCA (Highest Tier)",
      stat2Title: "London Head Office",
      stat2Desc: "192 Woodseer Street, London E1 5HQ",
      stat3Title: "15+ Years Experience",
      stat3Desc: "UK Tax, Accounting & Business Advisory"
    },
    about: {
      badge: "Principal Accountant",
      title: "Mrs. Anh Đào Carrick",
      subtitle: "BA, PG Cert, MA, FCCA | Senior Accountant",
      bio1: "Mrs. Anh Đào Carrick is a distinguished Fellow of the Association of Chartered Certified Accountants (FCCA) — the premier global accounting qualification. Holding postgraduate qualifications from top UK universities, she has dedicated over 15 years to advising businesses, entrepreneurs, and high-net-worth individuals.",
      bio2: "Operating directly from her London practice at 192 Woodseer Street, Mrs. Carrick assists Vietnamese entrepreneurs running businesses in the UK with clear, proactive, and compliant accounting and tax strategies.",
      fccaHighlight: "Qualified with FCCA — The Highest Tier of ACCA Professional Status",
      qualification1: "FCCA Fellow Member (Association of Chartered Certified Accountants, UK)",
      qualification2: "Master's Degree & Postgraduate Certifications from UK Universities",
      qualification3: "HMRC Registered Tax Agent & Digital MTD Specialist",
      qualification4: "Expert in Small-to-Medium Enterprise (SME) Tax Optimization & Start-Ups"
    },
    services: {
      badge: "Comprehensive Solutions",
      title: "Our Core Accounting & Business Services",
      subtitle: "Tailored, transparent, and proactive financial services designed to keep your business compliant and tax-efficient.",
      card1Title: "Statutory Year-End Accounts & Bookkeeping",
      card1Desc: "Full preparation of annual financial statements for Companies House and HMRC, monthly bookkeeping, management accounts, and cashflow reports.",
      card2Title: "Corporation Tax & Self-Assessment Returns",
      card2Desc: "Comprehensive tax planning and filing for Limited Companies (CT600) and sole traders/directors (Self-Assessment) maximizing legitimate allowances.",
      card3Title: "VAT Compliance & Making Tax Digital (MTD)",
      card3Desc: "VAT registration, threshold monitoring, quarterly returns under Making Tax Digital standards, and advice on Flat Rate vs. Standard VAT schemes.",
      card4Title: "PAYE Payroll & Workplace Pension",
      card4Desc: "Complete payroll processing, monthly payslips, P60/P45 generation, Real-Time Information (RTI) submissions to HMRC, and auto-enrolment pension setup.",
      card5Title: "UK Company Formation & Bank Account Setup",
      card5Desc: "Fast same-day company registration with Companies House, share structuring, registered London office address, and business bank account assistance.",
      card6Title: "Intellectual Property & Trademark Registration",
      card6Desc: "Protecting your brand identity, logo, and intellectual property rights with the UK Intellectual Property Office (UKIPO) and international registries.",
      card7Title: "Mergers, Acquisitions & Business Valuations",
      card7Desc: "Financial due diligence, company valuations, business sales/transfers, and restructuring advisory for growing enterprises.",
      card8Title: "Practical UK Accounting Training",
      card8Desc: "Hands-on professional training in UK accounting systems, Xero, QuickBooks, payroll operations, and UK bookkeeping standards.",
      card9Title: "Legal & Audit Network Referral",
      card9Desc: "Connecting clients with qualified solicitors, barristers, and statutory auditing partners for comprehensive business protection.",
      card10Title: "Business Growth & Development",
      card10Desc: "Strategic advisory, financial structuring, and business development for entrepreneurs in the United Kingdom."
    },
    sectors: {
      badge: "Industry Expertise",
      title: "Sectors We Specialize In",
      subtitle: "Deep practical experience serving Vietnamese-owned enterprises across the UK.",
      s1Title: "Nail Salons & Beauty Spas",
      s1Desc: "Tailored tax, VAT, chair rental, and payroll packages optimized for UK nail bars and aesthetic clinics.",
      s2Title: "Restaurants, Cafes & Takeaways",
      s2Desc: "Point-of-Sale integration, supplier cost accounting, VAT compliance, and food hospitality financial management.",
      s3Title: "Property Landlords & Real Estate",
      s3Desc: "SPV Limited Company setups for buy-to-let properties, Capital Gains Tax planning, and rental income accounts.",
      s4Title: "Contractors & Professional Freelancers",
      s4Desc: "IR35 reviews, dividend vs. salary optimization, and low-friction digital bookkeeping via cloud accounting apps.",
      s5Title: "E-Commerce & Retail Businesses",
      s5Desc: "Amazon/Shopify store accounts, VAT compliance, customs duty support, and multi-channel bookkeeping.",
      s6Title: "Investors & New UK Start-Ups",
      s6Desc: "UK company setup, financial forecasting, tax number registrations, and proactive business structuring."
    },
    deadlines: {
      badge: "HMRC Compliance",
      title: "Key UK Tax Deadlines You Must Know",
      subtitle: "Never miss a statutory filing deadline with Mrs. Anh Đào Carrick (FCCA) managing your calendar.",
      d1Title: "31st January",
      d1Subtitle: "Self-Assessment Tax Deadline",
      d1Desc: "Online filing deadline for individual tax returns and payment of balancing tax liabilities + 1st payment on account.",
      d2Title: "9 Months After Year-End",
      d2Subtitle: "Corporation Tax Payment",
      d2Desc: "Payment deadline for UK Corporation Tax to HMRC (due 9 months and 1 day after company accounting period ends).",
      d3Title: "12 Months After Year-End",
      d3Subtitle: "Company Accounts & CT600",
      d3Desc: "Statutory deadline to file annual accounts with Companies House (9 months) and CT600 tax return to HMRC (12 months).",
      d4Title: "Quarterly (1 Month + 7 Days)",
      d4Subtitle: "VAT Return & Payment",
      d4Desc: "Making Tax Digital (MTD) digital submission and payment deadline following the end of each VAT quarter period."
    },
    offices: {
      badge: "Contact & Head Office",
      title: "London Office Location & Direct Contact",
      subtitle: "Get in touch directly with Mrs. Anh Đào Carrick (FCCA) in London or via WhatsApp / Zalo.",
      londonTitle: "🇬🇧 London Head Office (United Kingdom)",
      londonWoodseer: "London Head Office",
      londonWoodseerAddr: "192 Woodseer Street, London, E1 5HQ, United Kingdom",
      phoneUKLabel: "UK Phone / WhatsApp / Viber / Zalo:",
      freephoneLabel: "UK Freephone Toll-Free:",
      emailLabel: "Official Email Enquiries:",
      hoursTitle: "Working Hours",
      hoursDesc: "Monday – Friday: 09:00 – 17:30 GMT | Saturday: By Appointment"
    },
    modal: {
      title: "Request an Accounting Consultation",
      subtitle: "Connect directly with Mrs. Anh Đào Carrick (FCCA) for a confidential assessment.",
      nameLabel: "Full Name *",
      phoneLabel: "Phone / WhatsApp / Zalo *",
      emailLabel: "Email Address *",
      serviceLabel: "Service Required",
      serviceOption1: "Year-End Statutory Accounts & Bookkeeping",
      serviceOption2: "Corporation Tax & Self-Assessment Return",
      serviceOption3: "VAT Return / Making Tax Digital (MTD)",
      serviceOption4: "UK Company Formation & Bank Account",
      serviceOption5: "Nail Salon / Restaurant Package",
      serviceOption6: "Property / Buy-to-Let Landlord Tax",
      serviceOption7: "Intellectual Property / Trademark",
      serviceOption8: "Mergers, Acquisitions & Training",
      messageLabel: "Brief details about your business or inquiry",
      submitWhatsApp: "📱 Send via WhatsApp (+44 749 013 0207)",
      submitZalo: "💬 Send via Zalo (+44 749 013 0207)",
      note: "Your information is strictly confidential under ACCA professional code of conduct."
    },
    footer: {
      rights: "© 2026 Anh Đào Carrick (FCCA). All Rights Reserved.",
      fccaNotice: "Accounting Practice directed by Mrs. Anh Đào Carrick (BA, PG Cert, MA, FCCA). Regulated under ACCA professional accounting standards.",
      quickLinks: "Quick Navigation",
      legalNotice: "London Office: 192 Woodseer Street, London, E1 5HQ, United Kingdom."
    }
  },

  vi: {
    nav: {
      home: "Trang Chủ",
      about: "Bà Anh Đào Carrick",
      services: "Dịch Vụ Kế Toán & Thuế",
      sectors: "Ngành Nghề Hỗ Trợ",
      deadlines: "Lịch Thuế HMRC",
      offices: "Văn Phòng",
      contact: "Liên Hệ",
      tagline: "Kế Toán ACCA Chuẩn Anh Quốc"
    },
    hero: {
      badge: "🇬🇧 Văn Phòng Kế Toán ACCA Chuẩn Anh Quốc",
      title: "Dịch Vụ Kế Toán & Khai Thuế UK Hàng Đầu Cho Doanh Nghiệp & Cộng Đồng Việt",
      subtitle: "Báo cáo tài chính, quyết toán thuế HMRC, thành lập công ty và tư vấn kinh doanh do Bà Anh Đào Carrick (BA, PG Cert, MA, FCCA) trực tiếp phụ trách.",
      ctaWhatsApp: "💬 Chat qua WhatsApp",
      ctaZalo: "💬 Chat qua Zalo",
      ctaConsultation: "Nhận Báo Giá Miễn Phí",
      stat1Title: "Kế Toán FCCA",
      stat1Desc: "Bằng cấp cao cấp nhất của Hiệp hội ACCA Anh Quốc",
      stat2Title: "Trụ Sở Chính London",
      stat2Desc: "192 Woodseer Street, London E1 5HQ",
      stat3Title: "15+ Năm Kinh Nghiệm",
      stat3Desc: "Chuyên sâu về thuế & pháp lý kinh doanh UK"
    },
    about: {
      badge: "Giám Đốc & Kế Toán Trưởng",
      title: "Bà Anh Đào Carrick",
      subtitle: "BA, PG Cert, MA, FCCA | Kế Toán Trưởng Cấp Cao",
      bio1: "Bà Anh Đào Carrick là Hội viên Cao cấp của Hiệp hội Kế toán Công chứng Hoàng gia Anh (FCCA - Fellow Chartered Certified Accountant) — tổ chức kế toán chuyên nghiệp danh giá hàng đầu thế giới. Với các văn bằng Thạc sĩ và sau đại học tại các trường đại học uy tín của Vương Quốc Anh, bà có hơn 15 năm kinh nghiệm thực tiễn đồng hành cùng các doanh nghiệp và kiều bào.",
      bio2: "Hoạt động trực tiếp từ văn phòng tại London (192 Woodseer Street), Bà Anh Đào Carrick mang lại giải pháp kế toán rõ ràng, chính xác, tiết kiệm thuế tối đa và đảm bảo 100% tuân thủ pháp luật Anh Quốc cho các doanh nghiệp, tiệm nail, nhà hàng và nhà đầu tư tại Anh.",
      fccaHighlight: "Được Cấp Chứng Chỉ Hành Nghề Kế Toán Trưởng FCCA Cao Cấp Nhất của ACCA",
      qualification1: "Hội viên Cao cấp FCCA (Hiệp hội Kế toán Công chứng Anh Quốc - ACCA)",
      qualification2: "Văn bằng Thạc sĩ (MA) & Chứng chỉ Sau Đại học (PG Cert) tại Anh Quốc",
      qualification3: "Đại lý Thuế được HMRC ủy quyền chính thức (HMRC Registered Tax Agent)",
      qualification4: "Chuyên gia tối ưu thuế & bảo vệ quyền lợi doanh nghiệp vừa và nhỏ (SMEs)"
    },
    services: {
      badge: "Dịch Vụ Toàn Diện",
      title: "Các Dịch Vụ Kế Toán & Thuế Cốt Lõi",
      subtitle: "Dịch vụ minh bạch, chính xác, tận tâm, giúp doanh nghiệp yên tâm phát triển kinh doanh bền vững.",
      card1Title: "Kế Toán Trọn Gói & Báo Cáo Tài Chính Năm",
      card1Desc: "Lập báo cáo tài chính năm nộp Companies House và HMRC, ghi chép sổ sách kế toán (Bookkeeping), báo cáo quản trị và kiểm soát dòng tiền.",
      card2Title: "Quyết Toán Thuế Doanh Nghiệp (CT600) & Thuế Cá Nhân",
      card2Desc: "Khai thuế thu nhập doanh nghiệp (Corporation Tax) và thuế thu nhập cá nhân (Self-Assessment) cho chủ tiệm, giám đốc, tối ưu các khoản giảm trừ hợp pháp.",
      card3Title: "Kê Khai Thuế GTGT (VAT) & Chuẩn MTD",
      card3Desc: "Đăng ký mã số VAT, tư vấn phương pháp VAT (Flat Rate Scheme / Standard Scheme), nộp tờ khai VAT định kỳ theo chuẩn kỹ thuật số Making Tax Digital.",
      card4Title: "Quản Lý Bảng Lương (PAYE) & Lương Hưu",
      card4Desc: "Tính lương hàng tháng (Payroll), xuất phiếu lương (Payslips), tờ khai P60/P45, báo cáo thời gian thực RTI tới HMRC và đăng ký quỹ hưu trí bắt buộc.",
      card5Title: "Thành Lập Công Ty UK & Mở Tài Khoản Ngân Hàng",
      card5Desc: "Đăng ký thành lập công ty TNHH (Limited) lấy mã số ngay trong ngày, cấu trúc cổ phần, cung cấp địa chỉ văn phòng tại London và hỗ trợ mở tài khoản ngân hàng.",
      card6Title: "Bảo Hộ Sở Hữu Trí Tuệ & Đăng Ký Thương Hiệu",
      card6Desc: "Tư vấn và nộp đơn đăng ký bảo hộ nhãn hiệu, logo, thương hiệu độc quyền tại Cục Sở hữu Trí tuệ Anh Quốc (UKIPO) và quốc tế.",
      card7Title: "Tư Vấn Mua Bán, Sáp Nhập & Định Giá Doanh Nghiệp",
      card7Desc: "Thẩm định tài chính (Due Diligence), định giá tiệm/doanh nghiệp khi sang nhượng, hỗ trợ hợp đồng và tái cơ cấu doanh nghiệp.",
      card8Title: "Đào Tạo Kế Toán Thực Hành Chuẩn UK",
      card8Desc: "Khóa học thực chiến kế toán Anh Quốc, sử dụng thành thạo phần mềm kế toán Xero, QuickBooks, xử lý hồ sơ thuế thực tế cho học viên.",
      card9Title: "Mạng Lưới Luật Sư & Kiểm Toán Uy Tín",
      card9Desc: "Kết nối dịch vụ kiểm toán độc lập và giới thiệu luật sư uy tín xử lý mọi vấn đề pháp lý doanh nghiệp tại Anh Quốc.",
      card10Title: "Phát Triển & Mở Rộng Doanh Nghiệp",
      card10Desc: "Tư vấn chiến lược mở rộng quy mô, tối ưu tài chính và xúc tiến kinh doanh bền vững tại Vương Quốc Anh."
    },
    sectors: {
      badge: "Lĩnh Vực Chuyên Nghiệp",
      title: "Các Ngành Nghề Chúng Tôi Phục Vụ",
      subtitle: "Am hiểu đặc thù kinh doanh thực tế của cộng đồng người Việt tại Anh Quốc.",
      s1Title: "Tiệm Nails & Thẩm Mỹ Viện (Beauty Salons)",
      s1Desc: "Gói kế toán chuyên biệt cho tiệm nail, xử lý thuế thợ (Self-employed / Chair rental), tối ưu VAT và chi phí nguyên vật liệu.",
      s2Title: "Nhà Hàng, Quán Ăn & Takeaway",
      s2Desc: "Tích hợp hệ thống máy tính tiền POS, quản lý chi phí đầu vào, kiểm soát VAT và kế toán lương nhân viên bếp & phục vụ.",
      s3Title: "Chủ Nhà Cho Thuê & Đầu Tư Bất Động Sản",
      s3Desc: "Thành lập công ty SPV mua nhà cho thuê (Buy-to-Let), tối ưu thuế chuyển nhượng, thuế thặng dư vốn (CGT) và khấu hao.",
      s4Title: "Nhà Thầu Độc Lập & Chuyên Gia (Contractors)",
      s4Desc: "Tư vấn quy chế IR35, cơ cấu tối ưu giữa tiền lương và cổ tức (Dividends) để tiết kiệm thuế thu nhập cá nhân tối đa.",
      s5Title: "Thương Mại Điện Tử & Bán Lẻ",
      s5Desc: "Kế toán cho gian hàng Amazon, eBay, TikTok Shop, xử lý thuế VAT và sổ sách bán hàng đa kênh.",
      s6Title: "Nhà Đầu Tư & Doanh Nghiệp Mới Khởi Nghiệp",
      s6Desc: "Hỗ trợ thành lập công ty, lập kế hoạch tài chính, xin mã số thuế và báo cáo minh bạch dòng tiền."
    },
    deadlines: {
      badge: "Lưu Ý Quan Trọng",
      title: "Các Mốc Hạn Thuế Quan Trọng Của HMRC",
      subtitle: "Đừng để bị phạt oan do nộp muộn — Bà Anh Đào Carrick (FCCA) sẽ quản lý lịch trình thuế cho bạn.",
      d1Title: "31 Tháng 1 Hàng Năm",
      d1Subtitle: "Hạn Chót Khai Thuế Cá Nhân (Self-Assessment)",
      d1Desc: "Hạn nộp tờ khai thuế thu nhập cá nhân qua mạng cho năm thuế trước và thanh toán số thuế còn nợ + tạm ứng thuế kỳ 1.",
      d2Title: "9 Tháng Sau Ngày Khóa Sổ",
      d2Subtitle: "Hạn Nộp Thuế Doanh Nghiệp (Corporation Tax)",
      d2Desc: "Doanh nghiệp phải thanh toán tiền thuế Corporation Tax cho HMRC chậm nhất là 9 tháng 1 ngày sau khi kết thúc năm tài chính.",
      d3Title: "12 Tháng Sau Ngày Khóa Sổ",
      d3Subtitle: "Hạn Nộp Tờ Khai CT600 & Báo Cáo Năm",
      d3Desc: "Hạn nộp báo cáo tài chính lên Companies House (trong 9 tháng) và nộp tờ khai quyết toán thuế CT600 lên HMRC (trong 12 tháng).",
      d4Title: "Hàng Quý (1 Tháng + 7 Ngày)",
      d4Subtitle: "Kê Khai & Nộp Tiền Thuế VAT",
      d4Desc: "Nộp tờ khai VAT kỹ thuật số theo chuẩn MTD và thanh toán số thuế GTGT trong vòng 1 tháng 7 ngày sau khi kết thúc kỳ VAT."
    },
    offices: {
      badge: "Thông Tin Liên Hệ & Trụ Sở",
      title: "Trụ Sở Tại London & Kênh Liên Hệ",
      subtitle: "Quý khách có thể liên hệ trực tiếp với Bà Anh Đào Carrick tại London hoặc qua Zalo / WhatsApp.",
      londonTitle: "🇬🇧 Trụ Sở Chính Tại London (Vương Quốc Anh)",
      londonWoodseer: "Địa Chỉ Văn Phòng London:",
      londonWoodseerAddr: "192 Woodseer Street, London, E1 5HQ, Vương Quốc Anh",
      phoneUKLabel: "Điện Thoại / WhatsApp / Viber / Zalo (UK):",
      freephoneLabel: "Điện Thoại Miễn Phí (UK Freephone):",
      emailLabel: "Email Tiếp Nhận Hồ Sơ:",
      hoursTitle: "Giờ Làm Việc",
      hoursDesc: "Thứ Hai – Thứ Sáu: 09:00 – 17:30 (Giờ London) | Thứ Bảy: Hẹn Trước"
    },
    modal: {
      title: "Đăng Ký Tư Vấn Kế Toán & Nhận Báo Giá",
      subtitle: "Trao đổi trực tiếp với Bà Anh Đào Carrick (FCCA) — Bảo mật thông tin tuyệt đối.",
      nameLabel: "Họ và Tên Quý Khách *",
      phoneLabel: "Số Điện Thoại / Zalo / WhatsApp *",
      emailLabel: "Địa Chỉ Email *",
      serviceLabel: "Dịch Vụ Cần Tư Vấn",
      serviceOption1: "Kế toán trọn gói & Báo cáo tài chính năm",
      serviceOption2: "Khai thuế Doanh nghiệp (CT600) & Thuế Cá nhân",
      serviceOption3: "Kê khai thuế VAT / Chuẩn số Making Tax Digital",
      serviceOption4: "Thành lập công ty UK & Mở tài khoản ngân hàng",
      serviceOption5: "Gói kế toán chuyên biệt cho Tiệm Nail / Nhà Hàng",
      serviceOption6: "Kế toán thuế Bất động sản / Mua nhà cho thuê",
      serviceOption7: "Đăng ký bảo hộ Thương hiệu & Sở hữu trí tuệ",
      serviceOption8: "Mua bán, định giá doanh nghiệp & Đào tạo kế toán",
      messageLabel: "Nội dung tóm tắt nhu cầu của Quý khách",
      submitWhatsApp: "📱 Gửi Yêu Cầu qua WhatsApp (+44 749 013 0207)",
      submitZalo: "💬 Gửi Yêu Cầu qua Zalo (+44 749 013 0207)",
      note: "Mọi thông tin của Quý khách được bảo mật nghiêm ngặt theo chuẩn mực đạo đức nghề nghiệp của ACCA."
    },
    footer: {
      rights: "© 2026 Anh Đào Carrick (FCCA). Bảo lưu mọi quyền.",
      fccaNotice: "Văn phòng Kế toán do Bà Anh Đào Carrick (BA, PG Cert, MA, FCCA) trực tiếp điều hành. Hoạt động tuân thủ theo tiêu chuẩn đạo đức và nghề nghiệp của Hiệp hội ACCA Anh Quốc.",
      quickLinks: "Liên Kết Nhanh",
      legalNotice: "Trụ sở chính: 192 Woodseer Street, London, E1 5HQ, Vương Quốc Anh."
    }
  }
};
